const property1 = [
  { id: 1,  name: "Arjun Kumar",     phone: "+91 98765 43210", profileImage: "https://randomuser.me/api/portraits/men/1.jpg",  paid: true },
  { id: 2,  name: "Sneha Patel",     phone: "+91 91234 56789", profileImage: "https://randomuser.me/api/portraits/women/2.jpg", paid: false },
  { id: 3,  name: "Rahul Sharma",    phone: "+91 99887 66554", profileImage: "https://randomuser.me/api/portraits/men/3.jpg",  paid: true },
  { id: 4,  name: "Ananya Singh",    phone: "+91 90909 80808", profileImage: "https://randomuser.me/api/portraits/women/4.jpg", paid: false },
  { id: 5,  name: "Vikram Rao",      phone: "+91 90123 45678", profileImage: "https://randomuser.me/api/portraits/men/5.jpg",  paid: true },

  { id: 6,  name: "Pooja Mehta",     phone: "+91 98231 22334", profileImage: "https://randomuser.me/api/portraits/women/6.jpg", paid: true },
  { id: 7,  name: "Karthik Reddy",   phone: "+91 99001 11223", profileImage: "https://randomuser.me/api/portraits/men/7.jpg",  paid: false },
  { id: 8,  name: "Neha Verma",      phone: "+91 93456 77889", profileImage: "https://randomuser.me/api/portraits/women/8.jpg", paid: true },
  { id: 9,  name: "Amit Joshi",      phone: "+91 97654 33221", profileImage: "https://randomuser.me/api/portraits/men/9.jpg",  paid: false },
  { id: 10, name: "Ritika Malhotra", phone: "+91 98876 55443", profileImage: "https://randomuser.me/api/portraits/women/10.jpg",paid: true },

  { id: 11, name: "Suresh Naik",     phone: "+91 99123 44556", profileImage: "https://randomuser.me/api/portraits/men/11.jpg", paid: false },
  { id: 12, name: "Kavya Iyer",      phone: "+91 90012 33445", profileImage: "https://randomuser.me/api/portraits/women/12.jpg",paid: true },
  { id: 13, name: "Rohan Das",       phone: "+91 95566 77880", profileImage: "https://randomuser.me/api/portraits/men/13.jpg", paid: false },
  { id: 14, name: "Nisha Kapoor",    phone: "+91 98989 12121", profileImage: "https://randomuser.me/api/portraits/women/14.jpg",paid: true },
  { id: 15, name: "Manoj Yadav",     phone: "+91 97777 88990", profileImage: "https://randomuser.me/api/portraits/men/15.jpg", paid: false },

  { id: 16, name: "Aishwarya Nair",  phone: "+91 98111 22334", profileImage: "https://randomuser.me/api/portraits/women/16.jpg",paid: true },
  { id: 17, name: "Deepak Chawla",   phone: "+91 99333 44556", profileImage: "https://randomuser.me/api/portraits/men/17.jpg", paid: false },
  { id: 18, name: "Shalini Gupta",   phone: "+91 98700 11223", profileImage: "https://randomuser.me/api/portraits/women/18.jpg",paid: true },
  { id: 19, name: "Praveen Kumar",   phone: "+91 96666 77889", profileImage: "https://randomuser.me/api/portraits/men/19.jpg", paid: false },
  { id: 20, name: "Meera Saxena",    phone: "+91 95432 10987", profileImage: "https://randomuser.me/api/portraits/women/20.jpg",paid: true },

  { id: 21, name: "Sanjay Mishra",   phone: "+91 98888 66777", profileImage: "https://randomuser.me/api/portraits/men/21.jpg", paid: false },
  { id: 22, name: "Priya Kulkarni",  phone: "+91 90009 87654", profileImage: "https://randomuser.me/api/portraits/women/22.jpg",paid: true },
  { id: 23, name: "Harish Bansal",   phone: "+91 91111 22333", profileImage: "https://randomuser.me/api/portraits/men/23.jpg", paid: false },
  { id: 24, name: "Swati Agarwal",   phone: "+91 92222 33444", profileImage: "https://randomuser.me/api/portraits/women/24.jpg",paid: true },
  { id: 25, name: "Naveen Pillai",   phone: "+91 93333 55667", profileImage: "https://randomuser.me/api/portraits/men/25.jpg", paid: false },
];

const property2 = [
  {
    id: 26,
    name: "Rohit Sharma",
    profileImage: "https://randomuser.me/api/portraits/men/26.jpg",
    phone: "9876543226",
    paid: true,
  },
  {
    id: 27,
    name: "Ananya Singh",
    profileImage: "https://randomuser.me/api/portraits/women/27.jpg",
    phone: "9876543227",
    paid: false,
  },
  {
    id: 28,
    name: "Karthik R",
    profileImage: "https://randomuser.me/api/portraits/men/28.jpg",
    phone: "9876543228",
    paid: true,
  },
  {
    id: 29,
    name: "Sneha Patel",
    profileImage: "https://randomuser.me/api/portraits/women/29.jpg",
    phone: "9876543229",
    paid: false,
  },
  {
    id: 30,
    name: "Aman Verma",
    profileImage: "https://randomuser.me/api/portraits/men/30.jpg",
    phone: "9876543230",
    paid: true,
  },
  {
    id: 31,
    name: "Pooja Nair",
    profileImage: "https://randomuser.me/api/portraits/women/31.jpg",
    phone: "9876543231",
    paid: false,
  },
  {
    id: 32,
    name: "Suresh Kumar",
    profileImage: "https://randomuser.me/api/portraits/men/32.jpg",
    phone: "9876543232",
    paid: true,
  },
  {
    id: 33,
    name: "Meera Iyer",
    profileImage: "https://randomuser.me/api/portraits/women/33.jpg",
    phone: "9876543233",
    paid: true,
  },
  {
    id: 34,
    name: "Nikhil Jain",
    profileImage: "https://randomuser.me/api/portraits/men/34.jpg",
    phone: "9876543234",
    paid: false,
  },
  {
    id: 35,
    name: "Riya Gupta",
    profileImage: "https://randomuser.me/api/portraits/women/35.jpg",
    phone: "9876543235",
    paid: true,
  },
  {
    id: 36,
    name: "Deepak Yadav",
    profileImage: "https://randomuser.me/api/portraits/men/36.jpg",
    phone: "9876543236",
    paid: false,
  },
  {
    id: 37,
    name: "Kavya Rao",
    profileImage: "https://randomuser.me/api/portraits/women/37.jpg",
    phone: "9876543237",
    paid: true,
  },
  {
    id: 38,
    name: "Arjun Mehta",
    profileImage: "https://randomuser.me/api/portraits/men/38.jpg",
    phone: "9876543238",
    paid: true,
  },
  {
    id: 39,
    name: "Neha Malhotra",
    profileImage: "https://randomuser.me/api/portraits/women/39.jpg",
    phone: "9876543239",
    paid: false,
  },
  {
    id: 40,
    name: "Vikas Singh",
    profileImage: "https://randomuser.me/api/portraits/men/40.jpg",
    phone: "9876543240",
    paid: true,
  },
  {
    id: 41,
    name: "Aishwarya Kulkarni",
    profileImage: "https://randomuser.me/api/portraits/women/41.jpg",
    phone: "9876543241",
    paid: true,
  },
  {
    id: 42,
    name: "Rahul Das",
    profileImage: "https://randomuser.me/api/portraits/men/42.jpg",
    phone: "9876543242",
    paid: false,
  },
  {
    id: 43,
    name: "Shalini Mishra",
    profileImage: "https://randomuser.me/api/portraits/women/43.jpg",
    phone: "9876543243",
    paid: true,
  },
  {
    id: 44,
    name: "Manoj Patil",
    profileImage: "https://randomuser.me/api/portraits/men/44.jpg",
    phone: "9876543244",
    paid: false,
  },
  {
    id: 45,
    name: "Divya Choudhary",
    profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
    phone: "9876543245",
    paid: true,
  },
  {
    id: 46,
    name: "Sanjay Reddy",
    profileImage: "https://randomuser.me/api/portraits/men/46.jpg",
    phone: "9876543246",
    paid: false,
  },
  {
    id: 47,
    name: "Nandini Joshi",
    profileImage: "https://randomuser.me/api/portraits/women/47.jpg",
    phone: "9876543247",
    paid: true,
  },
  {
    id: 48,
    name: "Akash Pandey",
    profileImage: "https://randomuser.me/api/portraits/men/48.jpg",
    phone: "9876543248",
    paid: true,
  },
  {
    id: 49,
    name: "Ishita Banerjee",
    profileImage: "https://randomuser.me/api/portraits/women/49.jpg",
    phone: "9876543249",
    paid: false,
  },
  {
    id: 50,
    name: "Pranav Kulkarni",
    profileImage: "https://randomuser.me/api/portraits/men/50.jpg",
    phone: "9876543250",
    paid: true,
  },
];

const property3 = [
  {
    id: 51,
    name: "Harish Bansal",
    profileImage: "https://randomuser.me/api/portraits/men/51.jpg",
    phone: "9876543251",
    paid: true,
  },
  {
    id: 52,
    name: "Sonal Aggarwal",
    profileImage: "https://randomuser.me/api/portraits/women/52.jpg",
    phone: "9876543252",
    paid: false,
  },
  {
    id: 53,
    name: "Abhishek Tiwari",
    profileImage: "https://randomuser.me/api/portraits/men/53.jpg",
    phone: "9876543253",
    paid: true,
  },
  {
    id: 54,
    name: "Ritika Kapoor",
    profileImage: "https://randomuser.me/api/portraits/women/54.jpg",
    phone: "9876543254",
    paid: false,
  },
  {
    id: 55,
    name: "Naveen Shetty",
    profileImage: "https://randomuser.me/api/portraits/men/55.jpg",
    phone: "9876543255",
    paid: true,
  },
  {
    id: 56,
    name: "Priyanka S",
    profileImage: "https://randomuser.me/api/portraits/women/56.jpg",
    phone: "9876543256",
    paid: true,
  },
  {
    id: 57,
    name: "Lokesh Kumar",
    profileImage: "https://randomuser.me/api/portraits/men/57.jpg",
    phone: "9876543257",
    paid: false,
  },
  {
    id: 58,
    name: "Tanvi Deshpande",
    profileImage: "https://randomuser.me/api/portraits/women/58.jpg",
    phone: "9876543258",
    paid: true,
  },
  {
    id: 59,
    name: "Sunil Chawla",
    profileImage: "https://randomuser.me/api/portraits/men/59.jpg",
    phone: "9876543259",
    paid: false,
  },
  {
    id: 60,
    name: "Bhavya Jain",
    profileImage: "https://randomuser.me/api/portraits/women/60.jpg",
    phone: "9876543260",
    paid: true,
  },
  {
    id: 61,
    name: "Ramesh Naik",
    profileImage: "https://randomuser.me/api/portraits/men/61.jpg",
    phone: "9876543261",
    paid: false,
  },
  {
    id: 62,
    name: "Simran Kaur",
    profileImage: "https://randomuser.me/api/portraits/women/62.jpg",
    phone: "9876543262",
    paid: true,
  },
  {
    id: 63,
    name: "Ajay Mallick",
    profileImage: "https://randomuser.me/api/portraits/men/63.jpg",
    phone: "9876543263",
    paid: true,
  },
  {
    id: 64,
    name: "Neelam Arora",
    profileImage: "https://randomuser.me/api/portraits/women/64.jpg",
    phone: "9876543264",
    paid: false,
  },
  {
    id: 65,
    name: "Kunal Saxena",
    profileImage: "https://randomuser.me/api/portraits/men/65.jpg",
    phone: "9876543265",
    paid: true,
  },
  {
    id: 66,
    name: "Pallavi Kulkarni",
    profileImage: "https://randomuser.me/api/portraits/women/66.jpg",
    phone: "9876543266",
    paid: true,
  },
  {
    id: 67,
    name: "Mohan Lal",
    profileImage: "https://randomuser.me/api/portraits/men/67.jpg",
    phone: "9876543267",
    paid: false,
  },
  {
    id: 68,
    name: "Aarti Sharma",
    profileImage: "https://randomuser.me/api/portraits/women/68.jpg",
    phone: "9876543268",
    paid: true,
  },
  {
    id: 69,
    name: "Vinod Khanna",
    profileImage: "https://randomuser.me/api/portraits/men/69.jpg",
    phone: "9876543269",
    paid: false,
  },
  {
    id: 70,
    name: "Shreya Sen",
    profileImage: "https://randomuser.me/api/portraits/women/70.jpg",
    phone: "9876543270",
    paid: true,
  },
  {
    id: 71,
    name: "Ashok Pillai",
    profileImage: "https://randomuser.me/api/portraits/men/71.jpg",
    phone: "9876543271",
    paid: false,
  },
  {
    id: 72,
    name: "Rupal Shah",
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    phone: "9876543272",
    paid: true,
  },
  {
    id: 73,
    name: "Vivek Tripathi",
    profileImage: "https://randomuser.me/api/portraits/men/73.jpg",
    phone: "9876543273",
    paid: true,
  },
  {
    id: 74,
    name: "Kriti Malviya",
    profileImage: "https://randomuser.me/api/portraits/women/74.jpg",
    phone: "9876543274",
    paid: false,
  },
  {
    id: 75,
    name: "Siddharth Bose",
    profileImage: "https://randomuser.me/api/portraits/men/75.jpg",
    phone: "9876543275",
    paid: true,
  },
  {
    id: 76,
    name: "Monika Verma",
    profileImage: "https://randomuser.me/api/portraits/women/76.jpg",
    phone: "9876543276",
    paid: false,
  },
  {
    id: 77,
    name: "Rohin Mehra",
    profileImage: "https://randomuser.me/api/portraits/men/77.jpg",
    phone: "9876543277",
    paid: true,
  },
  {
    id: 78,
    name: "Ankita Kuldeep",
    profileImage: "https://randomuser.me/api/portraits/women/78.jpg",
    phone: "9876543278",
    paid: true,
  },
  {
    id: 79,
    name: "Mahesh Gowda",
    profileImage: "https://randomuser.me/api/portraits/men/79.jpg",
    phone: "9876543279",
    paid: false,
  },
  {
    id: 80,
    name: "Swati Kulshreshtha",
    profileImage: "https://randomuser.me/api/portraits/women/80.jpg",
    phone: "9876543280",
    paid: true,
  },
];


export { property1, property2, property3 };