const places = [
    {
      id: 1,
      image: require("./assets/house-1.jpg"),
      name: "Greenwood Hostel",
      location: "New York, USA",
      rating: 4.5,
      type: "Hostel",
      liked: false, 
    },
    {
      id: 2,
      image: require("./assets/house-2.jpg"),
      name: "Skyline Apartments",
      location: "Los Angeles, USA",
      rating: 4.7,
      type: "Apartment",
      liked: false, 
    },
    {
      id: 3,
      image: require("./assets/house-3.jpg"),
      name: "Downtown To-let",
      location: "Chicago, USA",
      rating: 4.2,
      type: "To-let",
      liked: false, 
    },
    {
      id: 4,
      image: require("./assets/house-4.jpg"),
      name: "Grand Palace Hotel",
      location: "Miami, USA",
      rating: 4.8,
      type: "Hotel",
      liked: false, 
    },
    {
      id: 6,
      image: require("./assets/house-5.jpg"),
      name: "Sunrise Hostel",
      location: "San Francisco, USA",
      rating: 4.3,
      type: "Hostel",
      liked: false, 
    },
    {
        id: 7,
        image: require("./assets/house-1.jpg"),
        name: "Greenwood Hostel",
        location: "New York, USA",
        rating: 4.5,
        type: "Hostel",
        liked: false, 
      },
      {
        id: 8,
        image: require("./assets/house-2.jpg"),
        name: "Skyline Apartments",
        location: "Los Angeles, USA",
        rating: 4.7,
        type: "Apartment",
        liked: false, 
      },
      {
        id: 9,
        image: require("./assets/house-3.jpg"),
        name: "Downtown To-let",
        location: "Chicago, USA",
        rating: 4.2,
        type: "To-let",
        liked: false, 
      },
      {
        id: 10,
        image: require("./assets/house-4.jpg"),
        name: "Grand Palace Hotel",
        location: "Miami, USA",
        rating: 4.8,
        type: "Hotel",
        liked: false, 
      },
      {
        id: 11,
        image: require("./assets/house-5.jpg"),
        name: "Sunrise Hostel",
        location: "San Francisco, USA",
        rating: 4.3,
        type: "Hostel",
        liked: false,
      },
      {
        id: 12,
        image: require("./assets/house-1.jpg"),
        name: "Greenwood Hostel",
        location: "New York, USA",
        rating: 4.5,
        type: "Hostel",
        liked: false,
      },
      {
        id: 13,
        image: require("./assets/house-2.jpg"),
        name: "Skyline Apartments",
        location: "Los Angeles, USA",
        rating: 4.7,
        type: "Apartment",
        liked: false,
      },
      {
        id: 14,
        image: require("./assets/house-3.jpg"),
        name: "Downtown To-let",
        location: "Chicago, USA",
        rating: 4.2,
        type: "To-let",
        liked: false,
      },
      {
        id: 15,
        image: require("./assets/house-4.jpg"),
        name: "Grand Palace Hotel",
        location: "Miami, USA",
        rating: 4.8,
        type: "Hotel",
        liked: false,
      },
      {
        id: 16,
        image: require("./assets/house-5.jpg"),
        name: "Sunrise Hostel",
        location: "San Francisco, USA",
        rating: 4.3,
        type: "Hostel",
        liked: false,
      },
  ];
  
  export default places;
  